### ISSUE TITLE
AttributeError: AUX_TASKS

### ISSUE THREAD

**Issue by NUSShao** [yilundu/crl#3]
I try to use run.py as directed in your README.md, but it showed that in line 130, run.py:

`train_sensors = config.RL.AUX_TASKS.required_sensors`,

and it will cause the error:

```
Traceback (most recent call last):
  File "/home/nusshao/github/crl/habitat_baselines/run.py", line 230, in <module>
    main()
  File "/home/nusshao/github/crl/habitat_baselines/run.py", line 79, in main
    ckpt_wrapper(**vars(args))
  File "/home/nusshao/github/crl/habitat_baselines/run.py", line 84, in ckpt_wrapper
    run_exp(exp_config, run_type, ckpt_path=ckpt_path, run_id=run_id, run_suffix=run_suffix, opts=opts)
  File "/home/nusshao/github/crl/habitat_baselines/run.py", line 136, in run_exp
    train_sensors = config.RL.AUX_TASKS.required_sensors
  File "/home/nusshao/anaconda3/envs/habitat1.6/lib/python3.7/site-packages/yacs-0.1.8-py3.7.egg/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: AUX_TASKS
```

I tried to find the AUX_TASKS tag in the config files but failed.

**Comment by WangJuan6** [comment]
Hi, did you solve this problem? I have the same problem. 
Thanks
